name: CI
on:
  push:
    branches: "*"
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          DATABASE_HOST: ec2-3-224-164-189.compute-1.amazonaws.com
          DATABASE_USER: jhkephbsndwwml
          TEST_DATABASE: dc78tgk0q076qh
          DATABASE_PASSWORD: 090cae6d0e6c21e338d8e83b2ac1a85db99ea24b0d3c8d96a009657cab77bb36
          DATABASE_PORT: 5432
          NODE_ENV: ${{secrets.NODE_ENV}}
          PORT: ${{secrets.PORT}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
          JWT_COOKIE_EXPIRES_IN: ${{secrets.JWT_COOKIE_EXPIRES_IN}}
        ports:
          - 5432:5432  
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        node-version: [16.x]
        

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test