'on':
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        node-version:
          - 16.x
        os:
          - ubuntu-latest
    env:
      TEST_DATABASE_HOST: ${{secrets.DATABASE_HOST}}
      TEST_DATABASE_USER: ${{secrets.DATABASE_USER}}
      TEST_DATABASE: ${{secrets.TEST_DATABASE}}
      TEST_DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      TEST_DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      TEST_GIT_ACTIONS: ${{secrets.TEST_GIT_ACTIONS}}
      NODE_ENV: ${{secrets.NODE_ENV}}
      PORT: ${{secrets.PORT}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
      JWT_COOKIE_EXPIRES_IN: ${{secrets.JWT_COOKIE_EXPIRES_IN}}
     
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
      - run: npm install
      - run: npm test